name: vm

services:
  kepler:
    image: quay.io/sustainable_computing_io/kepler:latest
    ports:
      - 9100:9100
    privileged: true
    pid: host
    networks:
      - kepler-network
    volumes:
      - type: bind
        source: /proc
        target: /proc
      - type: bind
        source: /sys
        target: /sys
      - type: bind
        source: ./kepler/etc/kepler
        target: /etc/kepler

      # NOTE: use the models from the local repo
      - type: bind
        source: ../../../../data
        target: /var/lib/kepler/data

        # NOTE: for estimator - kepler communication
      - kepler-tmp:/tmp

    healthcheck:
      test: curl -f http://localhost:9100/metrics || exit 1
      interval: ${HEALTHCHECK_INTERVAL:-50s}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}

    cap_add:
      - ALL

    entrypoint:
      - /usr/bin/bash
      - -c

    command:
      - echo "Waiting for estimator socket";
        until [[ -e /tmp/estimator.sock ]]; do
        echo " ... waiting for socket";
        sleep 1;
        done;
        echo "starting kepler";
        set -x;
        /usr/bin/kepler
        -address="0.0.0.0:9100"
        -v="8"

  estimator:
    entrypoint:
      - python3.10
    command:
      - -u
      - src/kepler_model/estimate/estimator.py
    image: quay.io/sustainable_computing_io/kepler_model_server:v0.7.11-2

    volumes:
      - type: bind
        source: ./kepler/etc/kepler
        target: /etc/kepler

      - kepler-tmp:/tmp
      - estimator-mnt:/mnt
    networks:
      - kepler-network
      - model-server-network

  model-server:
    entrypoint:
      - python3.10
    ports:
      - 8100
    command:
      - -u
      - src/kepler_model/server/model_server.py
    image: quay.io/sustainable_computing_io/kepler_model_server:v0.7.11-2
    volumes:
      - type: bind
        source: ./kepler/etc/kepler
        target: /etc/kepler
      - model-server-mnt:/mnt
    networks:
      - model-server-network

volumes:
  # for kepler - estimator sock
  kepler-tmp:

  # for downloading models
  estimator-mnt:
  model-server-mnt:

networks:
  kepler-network:
  model-server-network:
