# scc for the Kepler
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: kepler-scc
# To allow running privilegedContainers
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: false
allowHostPorts: false
allowHostIPC: false
allowHostPID: true
readOnlyRootFilesystem: true
defaultAddCapabilities:
  - SYS_ADMIN
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
volumes:
  - configMap
  - projected
  - emptyDir
  - hostPath
  - secret
users:
  - $(KEPLER_NAMESPACE)
  - system:serviceaccount:$(KEPLER_NAMESPACE):kepler-sa
