scrape_configs:
- job_name: 'dev'
  static_configs:
    - targets: ['kepler-dev:8888']

- job_name: 'mock-acpi'
  static_configs:
    - targets: ['mock-acpi:8000']

- job_name: 'intel-pcm'
  static_configs:
    - targets: ['intel-pcm:9738']
  # metric_relabel_configs:
  #   - source_labels: [ __name__ ]
  #     target_label: __name__
  #     regex: '(.*)'
  #     action: replace
  #     replacement: pcm_${1}

- job_name: 'turbostat'
  static_configs:
    - targets: ['turbostat:8001']
