scrape_configs:
- job_name: 'vm'
  static_configs:
    - targets: ['vm:9100']

- job_name: 'scaphandre'
  static_configs:
    - targets: ['scaphandre:8080']

- job_name: 'metal'
  static_configs:
    - targets: ['kepler-metal:8888']
