name: monitoring

services:
  prometheus:
    build:
      context: ./prometheus
    ports:
      - 9090:9090
    volumes:
      - prom-data:/prometheus
      - type: bind
        source: ./prometheus/prometheus.yml
        target: /etc/prometheus/prometheus.yml
    networks:
      - monitoring

    healthcheck:
      test: wget -q --spider http://localhost:9090/ -O /dev/null || exit 1
      interval: ${HEALTHCHECK_INTERVAL:-50s}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}

  grafana:
    build:
      context: ./grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin

    user: "1000" # NOTE: change this to your `id -u`
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      - monitoring

    healthcheck:
      test: curl -f http://localhost:3000/ || exit 1
      interval: ${HEALTHCHECK_INTERVAL:-50s}
      timeout: ${HEALTHCHECK_TIMEOUT:-30s}
      retries: ${HEALTHCHECK_RETRIES:-3}
      start_period: ${HEALTHCHECK_START_PERIOD:-1m}

volumes:
  # volume for holding prometheus (ts)db
  prom-data:

networks:
  monitoring:
