# This workflow would be run on sustainable-computing-io/kepler only.
name: Scheduled build
on:
  workflow_dispatch:
  branch_protection_rule:
  schedule:
    - cron: "12 9 * * *"

jobs:
  # daily go security
  gosec:
    if: github.repository == 'sustainable-computing-io/kepler'
    uses: ./.github/workflows/gosec.yml
  # daily base image build and image build
  image_base:
    if: github.repository == 'sustainable-computing-io/kepler'
    uses: ./.github/workflows/image_base.yml
    secrets:
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}
  image:
    needs: [image_base]
    uses: ./.github/workflows/image.yml
    secrets:
        username: ${{ secrets.BOT_NAME }}
        password: ${{ secrets.BOT_TOKEN }}
  # daily openSSF scan
  scorecard:
    if: github.repository == 'sustainable-computing-io/kepler'
    uses: ./.github/workflows/scorecard.yml
  # daily rpm
  rpm:
    if: github.repository == 'sustainable-computing-io/kepler'
    uses: ./.github/workflows/rpm.yml
