---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  name: 50-master-kernel-devel-cgroupv2
  labels:
    machineconfiguration.openshift.io/role: master
spec:
  kernelArguments:
    - systemd.unified_cgroup_hierarchy=1
    - cgroup_no_v1="all"
  extensions:
  - kernel-devel